Repository astarte-platform/stream-qt5-test, pull requests merged in 2020-02, with the labels that each got.

#3 Dockerfile: update base builder image
  Dockerfile
Labels: blocking, bug

#5 Use standard-interfaces
  CHANGELOG.md
  Dockerfile
  interfaces/org.astarte-platform.genericsensors.Values.json
  interfaces/org.astarteplatform.Values.json
Labels: enhancement, user experience

#6 Use astartectl instead of python snippet
  README.md
Labels: documentation, user experience

#7 Prepare Astarte 0.11.0-rc.0
  CHANGELOG.md
  Dockerfile
Labels: chore
